# Generated by Django 3.2.13 on 2022-08-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubSetor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.setor')),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sub_setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.subsetor')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('data', models.DateTimeField(verbose_name='data')),
                ('preco_corrente', models.FloatField(default=0)),
                ('preco_medio', models.FloatField(default=0)),
                ('preco_compra', models.FloatField(default=0)),
                ('preco_venda', models.FloatField(default=0)),
                ('preco_venda_maximo', models.FloatField(default=0)),
                ('dias_operacao_compra', models.IntegerField(default=0)),
                ('dias_operacao_venda', models.IntegerField(default=0)),
                ('votos', models.IntegerField(default=0)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.acao')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10)),
                ('classificacao', models.CharField(default='   ', max_length=10)),
                ('segmento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.segmento')),
            ],
        ),
        migrations.AddField(
            model_name='acao',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.empresa'),
        ),
    ]
