# Generated by Django 3.2.13 on 2023-01-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230110_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.plano'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projecao_acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.projecaoacao'),
        ),
    ]
