# Generated by Django 3.2.13 on 2023-01-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230111_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='plano',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.plano'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='projecao_acao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.projecaoacao'),
        ),
    ]
