# Generated by Django 4.1.5 on 2023-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230111_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('ordem', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=40)),
                ('caption', models.CharField(max_length=40)),
                ('color', models.CharField(default='default', max_length=20)),
            ],
            options={
                'db_table': 'home_menu_grupo',
                'ordering': ['ordem', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('ordem', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=20)),
                ('icon', models.CharField(max_length=30, null=True)),
                ('title', models.CharField(max_length=40)),
                ('caption', models.CharField(max_length=40)),
                ('color', models.CharField(default='default', max_length=20)),
                ('target', models.BooleanField(default=False)),
                ('external', models.CharField(max_length=40)),
                ('url', models.CharField(max_length=60)),
                ('breadcrumbs', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'home_menu_item',
                'ordering': ['ordem', 'title'],
            },
        ),
    ]
