# Generated by Django 4.1.5 on 2023-01-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_menugrupo_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menugrupo',
            name='caption',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='menugrupo',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='caption',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='external',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
