# Generated by Django 4.1.5 on 2023-01-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_menugrupo_caption_alter_menugrupo_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='grupo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.menugrupo'),
            preserve_default=False,
        ),
    ]
