# Generated by Django 4.1.5 on 2023-01-12 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_menuitem_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='grupo',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pai',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem'),
            preserve_default=False,
        ),
    ]
