# Generated by Django 4.1.5 on 2023-01-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_menuitem_grupo_menuitem_pai'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuGrupo',
        ),
    ]
