# Generated by Django 4.1.5 on 2023-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_delete_menugrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='breadcrumbs',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
