# Generated by Django 4.1.5 on 2023-01-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_menuitem_breadcrumbs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='pai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.menuitem'),
        ),
    ]
