# Generated by Django 4.1.5 on 2023-01-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_menuitem_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='nome_configuracao',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
