# Generated by Django 4.1.5 on 2023-01-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_menuitem_nome_configuracao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['pai', 'ordem', 'title']},
        ),
    ]
