# Generated by Django 4.1.5 on 2023-01-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_menuitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['ordem', 'title']},
        ),
    ]
