# Generated by Django 4.1.5 on 2023-01-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_menuitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='id_name',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='id',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
