# Generated by Django 4.1.5 on 2023-01-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_remove_menuitem_id_name_alter_menuitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_ranking',
            field=models.BooleanField(default=True),
        ),
    ]
