# Generated by Django 4.1.5 on 2023-01-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_projecao_acao_profile_projecaoacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='menu_robo',
            field=models.BooleanField(default=True),
        ),
    ]
