# Generated by Django 4.1.5 on 2023-01-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_profile_menu_robo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='menu_ranking',
            field=models.BooleanField(default=False),
        ),
    ]
