# Generated by Django 4.1.5 on 2023-01-21 15:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_profile_menu_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='perfil',
            field=models.CharField(choices=[('a', 'Agressivo'), ('m', 'Moderado'), ('c', 'Conservador')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='primeiro_nome',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='ultimo_nome',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
