# Generated by Django 4.1.5 on 2023-01-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_profile_email_profile_perfil_profile_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='endereco',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
