# Generated by Django 4.1.5 on 2023-01-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_profile_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telefone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
